apexcharts/apexcharts.js

- src/locales/pt.json
Hi! This is a brazilian portuguese locale. Still untested, just started learning Apexcharts.
I used "pt" as the code, but some libs use ptBR, pt-BR, pt_BR or even "br". Not sure about which one do you prefer.
> Add brazilian portuguese locale

- src/apexcharts.js
- src/modules/Legend.js
- tests/e2e/snapshots/.gitignore
Create a new method to reset all current toggles made by `chart.toggleSeries`
#206
> Add resetToggleSeries functionality

- src/modules/Legend.js
Fixes typo for `inactive-legend` classList.
> Fix typo for 'inactive-legend' class

- src/modules/Annotations.js
Adds ability to add class to annotation markers
Missing ability to add class mentioned in #325
> adds cssClass onto point annotation markers

- src/modules/Toolbar.js
Custom icons in toolbar
Example:
```javascript
toolbar: {
tools: {
download: false,
selection: true,
zoom: true,
zoomin: true,
zoomout: true,
pan: true,
reset: true,
customIcons: [{
icon: '<img src="/static/icons/split-chart.png">',
class: 'custom-icon',
index: 0,
click: function () {
console.log("split chart clicked")
}
}]
}
}
```
> custom icons in toolbar

- types/apexcharts.d.ts
Fix shared type in tooltip option
> Fixed: shared type

- src/utils/DateTime.js
Fixed unexpected converting x-axis datetime in to UTC.
> Update for correct work with local timezone

- types/apexcharts.d.ts
Make `redrawPaths` and `animate` optional parameters
> Mark optional parameters optional

- dist/locales/id.json
> Add Indonesian Locale

- src/apexcharts.js
Automatically updates the chart foreColor and tooltip theme when you update theme mode.
Changes the file:
src/apexcharts.js
Fixes [#459](https://github.com/apexcharts/apexcharts.js/issues/459)
> updating theme mode - fixes #459

- README.md
Update readme to add ruby wrapper.
> Add ruby wrapper

- README.md
The image is broken because the source seems to be wrong. I was hoping someone else would notice this too and make a pull request. But I guess nobody does, so here it is.
> Fix broken annotations image

- src/locales/tr.json
> added turkish language file

- types/apexcharts.d.ts
Fixes the issues I raised a few minutes ago.
Fixes # #879, #880 
> [#879, #880] Fix types for `plotOptions.bar.endingShape` and `stroke.colors`

- dist/locales/it.json
Italian locale has been added.
> Add italian locale

- .gitattributes
- src/assets/apexcharts.css
- src/modules/Legend.js
- src/utils/DetectElementResize.js
Fix Content Security Policy isses caused by injecting CSS styles into DOM. CSS instructions extracted from Legend module and DetectElementResize util. Tested in browser with `line` chart.
Local run `npm run test` is crashed so please run tests on your side before merging.
Fixes #727
> Fix CSP issues

- src/apexcharts.js
> fix reset zoom bug at sync line charts

- src/locales/hr.json
> Add Croatian locales

- types/apexcharts.d.ts
- Fix min and max type in yaxis option
- refs: https://apexcharts.com/docs/options/yaxis/#min
> Fixed: min and max type

- src/locales/fi.json
- src/locales/se.json
> Added Finnish and Swedish language

- types/apexcharts.d.ts
`highlightDataSeries`
~Fixes (issue)~
> Fixed typo in apexcharts.d.ts

- dist/locales/ca.json
> Added catalan locale

- src/locales/nl.json
> Added Dutch locale

- src/modules/TimeScale.js
- src/modules/dimensions/XAxis.js
> show starting and ending year for combo chart; make x-axis years denser

- dist/apexcharts.js
- src/modules/ZoomPanSelection.js
> Fix issue#1293: reset xaxis fails on multiple charts

- dist/locales/sl.json
- src/locales/sl.json
> Slovene locale [sl]

- dist/locales/sk.json
- src/locales/sk.json
> Slovak locale [sk]

- dist/locales/cs.json
- src/locales/cs.json
> Czech locale [cs]

- dist/locales/lt.json
- src/locales/lt.json
> Lithuanian locale [lt]

- dist/locales/nb.json
- src/locales/nb.json
> Norwegian locale [nb]

- dist/locales/pt.json
- src/locales/pt.json
> Portuguese locale [pt]

- types/apexcharts.d.ts
Add proprties (class,click) to customIcons.
> add proprties to customIcons

- README.md
Added link to Blazor-ApexCharts in the unofficial wrapper section
> Added Blazor-ApexChart as unofficial wrapper

- src/modules/tooltip/Utils.js
> Issue/1448 Fix showing NaN in date time x-axis when disabled legends in multi series line chart with straight line

- types/apexcharts.d.ts
Add AppendData to Apexcharts class
Add AppendData to Apexcharts class
> Add AppendData to Apexcharts class

- dist/locales/rs.json
- src/locales/rs.json
Added new locale for the Serbian language
> Added Serbian locale [rs]

- dist/locales/rs.json
- src/locales/rs.json
Sorry for the typo, this PR fixes it.
> Minor locale typo fix

- src/modules/helpers/Destroy.js
Fixes # https://github.com/apexcharts/vue-apexcharts/issues/275
> Add check for baseEl

- samples/source/bubble/simple-bubble.xml
Updated simple-bubble.xml to make data more intuitive
> Updated simple-bubble.xml

- src/charts/common/bar/DataLabels.js
Hi, this PR fixes [next problems](https://codepen.io/funkir/pen/jOrPXEj)
> fixed dataLabels positions

- src/modules/tooltip/Labels.js
> add tooltip title formatter for horizontal chart

- src/modules/Graphics.js
- src/modules/axes/XAxis.js
- src/modules/dimensions/Dimensions.js
Hi, this PR fixes [next problems](https://codepen.io/funkir/pen/KKgJLGg)
> fix xaxis label size when uses ellipsis

- README.md
> Add Svelte wrapper

- types/apexcharts.d.ts
Correct type definition for the exec method
Fixes #2367
> Change exec method namespace definition to support multiple args as parameter for the called function

- README.md
Fixes #2435
Changing the url since they lost the domain
> Fixes incorrect url

- src/modules/Crosshairs.js
Сhecking negative values for svg attributes and change it to zero value
Fixes #2520
> issues-2520 Error in console about negative value

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
Updated issues templates and added more options for issue creation
> Updated issue templates

- .github/workflows/node.js.yml
> fix(ci): removing the run against node 16

- .github/workflows/stale.yml
Updated settings for the stale bot action
> Stale bot setting supdate

- src/charts/common/bar/DataLabels.js
Fixes an issue where 0 was printed in stacked bar charts data labels. Also fixes an issue where negative values were not printed in stacked column/bar charts.
Fixes #2640, #2454 
> 0 printed in stacked bar chart; fixes #2454, fixes #2640

- src/modules/CoreUtils.js
Fixes the height of the bars to be compatible with the logarithmic scale.
Fixes #2909 
> fix height of bars to match logarithmic scale

- src/locales/lv.json
> Add LV locale

- types/apexcharts.d.ts
The API works by accessing `xaxis.group`, not `xaxis.labels.group`
Types
> Fix label group typings

- src/modules/Graphics.js
Fixes issues with missing hover states after selecting or deselecting a section of a chart.
Fixes #3021
> Fix issue #3021

- CONTRIBUTING.md
- src/modules/axes/XAxis.js
- src/modules/settings/Options.js
- types/apexcharts.d.ts
I have added a click event for x-axis labels. The event provides information about a `labelIndex` (in most cases, it corresponds to the ``dataPointIndex`` from event `click`)
> Handle click on label

- types/apexcharts.d.ts
bubble chart series types support.
> add new Type in ApexAxisChartSeries support Bubble Chart

- package-lock.json
- package.json
- src/modules/Exports.js
- tests/unit/download-csv.spec.js
- yarn.lock
I am trying to start using your library, and believe I have found an unrelated bug related to colors that I want to start investigating so that I can contribute the fixes.  To that end, I wanted to be able to run the unit tests and get to know how this project works.  I am very new to Javascript and the whole ecosystem (I have lots of experience with c++ and Java), so please forgive me any stupid errors and point me in the right direction.
This PR addresses an issue I had with the unit tests related to date/time conversion.  I see that you are based in India, and that explains why you don't see the issue, but I do.  The tests steps that fail are:
- https://github.com/apexcharts/apexcharts.js/blob/main/tests/unit/downlaod-csv.spec.js#L170
- …
> Fix export unit test for US Eastern Timezone

- src/modules/Fill.js
> concatenate default fill config with user supplied fill config

- src/modules/axes/XAxis.js
> Fix x axis title position

- src/charts/Pie.js
> check value original path on pieClicked - fixes #2258

- src/locales/da.json
**Adding Danish locale [da] with "da.json".**
Note that months are not capitalized in Danish unless it's the first word in a sentence. Dates are written as "28. marts 2023"("March 28, 2023" in US English)
> Danish locale [da]

- src/assets/apexcharts.css
- src/charts/Bar.js
- src/charts/BarStacked.js
- src/charts/RangeBar.js
Using Content-Security-Policy header with style-src brings console error in bar chart.
Fixes # (https://github.com/apexcharts/react-apexcharts/issues/522)
> remove style injection as attribute in bar charts (csp style-src fix)

- src/modules/legend/Legend.js
Extend onLegendHover to also work over  `.apex-legend-series`  element.
#2911 
> fix: hover and click on legend series

- CONTRIBUTING.md
- README.md
Hi, it's my first contribution to this project, any suggestions are welcome.
> docs: improve how to contribute

- src/apexcharts.js
- src/modules/helpers/InitCtxVariables.js
This change exposes 'isSeriesHidden' to the public API so that developers may consume the functionality.
> Expose 'isSeriesHidden' to public methods

- src/modules/tooltip/Utils.js
This is related to #3798. The problem here is that we add a new control points that will always be closest to user's cursor position that first ones.
@junedchhipa sorry for my prev PR. I've double check this one again. I'll be pleasue if you'll check this one and approve it. thanks a lot.
Fixes #3798 
> fix: detect positioning for leftmost values

- src/modules/Core.js
if array check is not correct this will return a boolean or an array. Now it will return the array or an array created with the single target.
Fixes # (issue) #4104
> Fixed an Is array check

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- CONTRIBUTING.md
- src/modules/legend/Helpers.js
- types/apexcharts.d.ts
Remove trailing spaces and replace tabs.
Please use EditorConfig extension in your IDE.
https://github.com/szepeviktor/byte-level-care/issues/97
> Remove trailing spaces and replace tabs

- src/modules/dimensions/Grid.js
> Issue #4178 fix

- src/modules/Scales.js
Scales.niceScale() was not observing xaxis option settings tickAmount, min and max when scaling horizontal bar charts. Bug introduced in 3.46.0.
Reinforce default bar (and column) chart zero baseline in case the user sets other options. Only override if the user sets min (all-positive data) or max (all-negative data).
Fixes #4254 (mostly). Previous changes included in 3.46.0 provide an interim solution to hideOverlappingLabels being not implemented for horizontal bar charts, namely the tick pruning feature incorporated within Scales.niceScale().
> Issue 4254: Partial resolution

- samples/react/column/stacked-column-with-line-new.html
- samples/react/column/stacked-column-with-line.html
- samples/react/misc/annotations-example.html
- samples/react/mixed/line-column-area.html
- samples/react/mixed/line-column.html
- samples/source/column/stacked-column-with-line-new.xml
- samples/source/column/stacked-column-with-line.xml
- samples/source/misc/annotations-example.xml
- samples/source/mixed/line-column-area.xml
- samples/source/mixed/line-column.xml
- samples/vanilla-js/column/stacked-column-with-line-new.html
- samples/vanilla-js/column/stacked-column-with-line.html
- samples/vanilla-js/misc/annotations-example.html
- samples/vanilla-js/mixed/line-column-area.html
- samples/vanilla-js/mixed/line-column.html
- samples/vue/column/stacked-column-with-line-new.html
- samples/vue/column/stacked-column-with-line.html
- samples/vue/misc/annotations-example.html
- samples/vue/mixed/line-column-area.html
- samples/vue/mixed/line-column.html
- src/modules/Range.js
Working on using the series style attribute to influence axis scaling for bars and columns, specifically referencing a zero baseline. Generally, only the chart type is used.
- [X ] New and existing unit tests pass locally with my changes
> Bar and Column chart ranges

- src/modules/annotations/PointsAnnotations.js
> Fix point annotation still visible when referenced series is collapsed.

- src/charts/Line.js
> RangeArea fix for smooth curves broke straight line rangeArea plots.

- src/charts/Line.js
> Lines from series with only two points were not rendering.

- src/locales/vi.json
> 🌐 Add vietnam locale

- src/modules/axes/AxesUtils.js
- src/modules/axes/YAxis.js
Fix yaxis offset calculated for heatmap charts with large series
Fixes #2033
before
after
> Fix heatmap yaxis offset

- types/apexcharts.d.ts
Can be a string or string array.
> seriesName type

- src/charts/BarStacked.js
- src/charts/common/bar/DataLabels.js
> Stacked column totals dataLabel position fix (category X-axis).

- src/charts/Line.js
> Fix issue #4471: path termination for irregular series.

- src/modules/Scales.js
> Remove declared but unused variables

- .github/workflows/codeql-analysis.yml
The current version of CodeQL being used (v1) has been superseded by v3. Upgrading the CodeQL actions gets rid of the warnings about CodeQL being outdated.
The CodeQL frequency has also been updated so it runs every day instead of every Saturday
> Updated CodeQL

- src/charts/BarStacked.js
- src/charts/common/bar/DataLabels.js
Although this change fixes the example in the issue, and all other samples in the package and my private collection appear to render correctly, it will have to be proven in use. I've attempted to base all computational changes on those first principals that the original code follows, as far as I understand them.
Fixes #4558
> Fix bar chart labels X-position calculations

- package-lock.json
- yarn.lock
The most recent commits to this repository are having their `npm ci` step in the workflows fail because the package.json and package-lock.json files are out of sync. Running `npm install` fixes that and syncs the files. This pull request adds the changes made by running `npm install`.
The Test & Build workflow steps are expected to fail as the `npm ci` step for the head repository will fail because of the out of sync files. The other workflows (Test Reproducibility & Lint) should succeed. Subsequent workflow runs won't face this issue after the files have been synced.
> Sync lockfiles

- src/charts/common/bar/DataLabels.js
Fixes #4647 
https://github.com/apexcharts/apexcharts.js/issues/4647
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [ x] My branch is up to date with any changes from the main branch
> Fix wrong datalabel value

- src/modules/Core.js
> Recent refactor broke rangeArea plots

- samples/vanilla-js/column/border-radius-test.html
- src/assets/apexcharts.css
- src/charts/Bar.js
- src/charts/BarStacked.js
- src/charts/Line.js
- src/charts/common/bar/Helpers.js
- src/modules/Range.js
improve border radius implementation in stacked bar charts
> improve border radius implementation in stacked bar charts

- src/modules/Fill.js
> Apply config opacity to fill colors specified in RGB format.

- types/apexcharts.d.ts
Updated the type of `goals` in `ApexAxisChartSeries.data` from `any` to specific type
> update goals type

- src/modules/tooltip/Tooltip.js
Reverts apexcharts/apexcharts.js#4929
> Revert "Fix tooltip stability for smoother chart interaction"

- src/modules/annotations/Helpers.js
> fix annotation clipping calculation caused by unprecise floats

- types/apexcharts.d.ts
> fix: the wrong return type of the formatter function
