src/modules/Series.js
I noticed a minor bug when I was looking at the color range demo on heatmap.
https://apexcharts.com/javascript-chart-demos/heatmap-charts/color-range/
when drawing the color range, it is selecting data inclusively but when selecting the legend to filter it, chart excludes the 'to' and 'from' values. this change might have adverse effect on other chart types. I haven't checked it myself yet..
Thanks
=> changed selectedActive to be inclusive

src/modules/ZoomPanSelection.js
I assume that **startX - 1** is duplicated
```php
let startX = me.startX - 1
```
```php
let selectionWidth = me.clientX - gridRectDim.left - startX - 1
```
Maybe related to #25
-  Bug fix (non-breaking change which fixes an issue)
-  My code follows the style guidelines of this project
- I have performed a self-review of my own code
=> fix negative <rect> attribute width error

src/modules/tooltip/Labels.js
As per #264 , on initial tooltip positioning it goes out of bounds. This happens because tooltip dimensions are calculated and then cached before the text in it is updated. This pull request makes sure the dimensions are re-calculated in case the text is updated. Ideally, this would happen in a more structured way (this way the calculation happens twice), but I believe that would require some major re-structuring of the code.
Fixes #264
=> Re-calculate tooltip dimensions on text draw

src/modules/Annotations.js
Following PR #338 , I adjusted the existence check for x2 and y2 properties with `x2 == null` instead of `!x2` and `y2 == null` instead of `!y2` to allow value of `0`.
Without this fix, having `x2` or `y2` with a value of `0` would make the annotation to be displayed as a single line, as the second property to make it a range annotation would be ignored.
=> Range annotations - Fixed existence check for x2 and y2 properties

src/charts/Bar.js
After further investigation of issue #260 , I have identified the bottleneck causing performance issue for bar charts.
In the `calculateDataLabelsPos` method of `charts\Bar.js`, there is a call to the `getTextRects` method to calculate the size of the dataLabels. This is what makes the performance to drop when having a lot of bars to display.
As a quick workaround, I added a check for whether the `dataLabels` option is enabled in the first place. If not, we simply skip this method altogether, preventing performance drop when not needed.
In addition to this, I was thinking of adding a threshold (arbitrary value) defining a maximum number of bars to allow DataLabels. If the maximum is reached, it could do one of the following:
- log a console warning in the console (e.g.: "DataLabels are …
=> Added check to prevent dataLabels calculation if the "dataLabel" option is disabled

samples/vanilla-js/column/stacked-column-empty-points.html, src/charts/BarStacked.js
This is a potential fix for the stacked charts issue (#352).
The idea is to check for all series for a corresponding X key instead of going only by index and previous index as it is now.
This way, even when having inconsistent X values, it will still find matching ones and stack accordingly.
- This particular PR only handles stacked **bar/column** currently. I still decided to submit it to get quick feedback and review on this. If accepted, we can then proceed to tackle other stacked chart types. Let me know.
=> Reviewed logic of calculating stacked bars in timeseries to account for inconsistent X values

types/apexcharts.d.ts
Looking at the [type definition](https://github.com/apexcharts/apexcharts.js/blob/master/types/apexcharts.d.ts#L62) I can see that `fontFamily` is required, but [here](https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/settings/Options.js#L234) it looks like this should be an optional property as it has a default.
The solution
Marked property optional in `apexcharts.d.ts`
=> Make `fontFamily` and `type` optional

dist/locales/de.json
This Pull Request fixes the abbreviation (`shortMonths`) of 'März'.
=> Fix an abbreviation in the DE locale

src/modules/Graphics.js
The correct attribute name is [dominant-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline).
=> Typo: dominate-baseline

src/locales/de.json
Short form of März is Mär not Mar in german.
Just changed one char within a string. :-)
No issue exists.
=> fixed typo in german locale

types/apexcharts.d.ts
My chart is using the number-pair tuple list version of data, as documented at
https://apexcharts.com/docs/series/
in section 2.1/3.1, but that wasn't a valid TypeScript type.
I just made the number-pair tuple list a valid type.
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] My changes generate no new warnings
=> Alfie j missing valid data type

src/charts/Pie.js
Fixed Error: <circle> attribute r: A negative value is not valid. 
Problem occurs in small pie donut chart if chart block resized.
=> fix: Error: <circle> attribute r: A negative value is not valid

src/charts/Bar.js
Datalabel styling configuration for a horizontal bar chart is not sufficient.
When the bar is not wide enough the text is hardly readable depending on back/front color.
Fixes #675 
It also fixes an issue that when you have stacked:true and hideOverflowingLabels: true it always hides negative value datalabels (see https://codepen.io/anon/pen/KjzJvr)
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Invert text anchor for negative values

src/apexcharts.js
Ensures series exists. Can occur when you pass in `[]` as a series.
=> Add check for existant series in updateOptions

types/apexcharts.d.ts
Added the type parameter for ApexAxisChartSeries, since it  and is used in the docs here: https://apexcharts.com/javascript-chart-demos/mixed-charts/multiple-yaxis/
It should not break existing TypeScript code since the parameter is optional. I tried it with some examples and it works. I don't know if this parameter works with every type of chart, if so, I can make the definition more specific.
=> Added type definition to ApexAxisChartSeries

src/modules/Scales.js
This fixes rounding errors in forceNiceScale
before, magMsd was 0 as a result of parseInt(0.99999999999)
Now it can't happen.
I believe this is a correct fix for  #759 #672
=> fix forceNiceScale for small values #759 #672

src/modules/Exports.js
Hi. We ran on an issue on our project where exported donut charts didn't have the proper hight (bottom legends were cut off).
After investigation, it appeared that exporting canvas' height was based on `svgHeight`, but `svgHeight` is actually not always representing the reality because of what `resizeNonAxisCharts` does.
So, maybe there is a better way, but I grabbed real hight from `dom.elWrap.style.height`.
=> Use the real chart's height when exporting image

types/apexcharts.d.ts
Add missing property `reversed` to ApexYAxis.
source: https://apexcharts.com/docs/options/yaxis/#reversed
=> Add missing `reversed` property

types/apexcharts.d.ts
- Consolidated various `dropShadow` definitions to a single `ApexDropShadow` type.
- Added extra `enabledOnSeries` and `color` properties specified in documentation to `dropShadow` definition in `ApexChart` type.
- Added missing `dropShadow` definition to `radialBar.hollow`.
- Fixed presumed missing `?` in `ApexDataLabels.dropShadow.enabled`.
None created
=> DropShadow Type Consolidation and Small Fixes

types/apexcharts.d.ts
Hi! As you have demonstrated in the following demo, you can use an array for the stroke width. This should be reflected in the official types.
https://apexcharts.com/javascript-chart-demos/mixed-charts/line-column/
TypeScript types
=> Add number[] to type of stroke.width

src/assets/apexcharts.css
Summary: Some CSS had disabled the click event on point annotations, x and y axis annotations as well.
No extra dependencies required.
Fixes: #1021
Change Type: Bug fix (non-breaking change which fixes an issue)
=> Fixes annotation click issue #1021

types/apexcharts.d.ts
Issue: setting labels color in **ng-apexcharts** doesn't work because `labels.color` in type `ApexLegend` should be `labels.colors`
=> Fix ApexLegend type in apexcharts.d.ts

types/apexcharts.d.ts
According to demos, data on `ApexAxisChartSeries` can be `null`.
https://apexcharts.com/javascript-chart-demos/line-charts/null-values/
So this PR added null types to `ApexAxisChartSeries`.
=> Fix: Chart series support null value as data

types/apexcharts.d.ts
Since v3.15.2 (maybe), xaxis formatter supports multiline labels. (ref. https://github.com/apexcharts/apexcharts.js/issues/670#issuecomment-578011468)
But type definition file is not updated, this PR fixed that.
When there are more formatters which support multiline please notice, I fix d.ts :)
=> Fix type definition file: support multiline labels

README.md, src/modules/Exports.js
This pull request is a partial fix for inability to download png in IE11 as discussed in issue https://github.com/apexcharts/apexcharts.js/issues/518. The caveat is that the exported image does not contain a legend. Fully fixing this issue would probably require a full rewrite of the legend code to generate svg elements instead of html.
This PR fixes the following problems, which previously prevented this feature from working:
- Fix the invalid svg string generated by IE11 using regex. 
- Use canvg in IE11 (if present) to generate canvas from svg, thus preventing a SecurityError from being thrown when we try to get image from the canvas.
- Remove usage of revokeObjectURL, since it serves only to release objects allocated with createObjectURL, which is not the case here. IE11 and Edge …
=> partially support png download in ie11

src/modules/helpers/UpdateHelpers.js
If seriesIndex / dataPointIndex is incorrect in toggleDataPointSelection it generates this error:
=> Skip getting elPath.node if element not found in toggleDataPointSelection

src/apexcharts.js, src/modules/Series.js
Calling `chart.updateOptions()` after `hideSeries(...)`  causes next issues:
1) `updateOptions({...})` should not change the state of hidden/visible series (the case in which no new series get passed).
2) after `updateOptions({...})` was called - it is impossible to toggle serie visibility back by clicking on legend.
Example here (blue timeserie is broken):
https://codepen.io/mallburn/pen/ZEGOZRK 
https://github.com/apexcharts/apexcharts.js/issues/655
https://github.com/apexcharts/apexcharts.js/issues/656
=> Hidden Series and updateOptions() issue fix

types/apexcharts.d.ts
add array type to  ApexStroke curve property.(at type definition)
=> add array type to ApexStroke Curve

dist/locales/pl.json
"Oddaj" means "give back"
"Oddal" means "zoom out" :-)
=> Fix wrong polish translation of zoomOut

src/apexcharts.js
ApexCharts documentation states next:
```
showForSingleSeries: Boolean
Show legend even if there is just 1 series.
```
But in case when 
- no series data (empty array)
- and only 1 serie for the chart
The legend doesn't shows up.
I think that `showForSingleSeries = true` flag should be main indicator for legend visibility and overwrite any other conditions.
I also spend some time trying to add tests, but 
- for unit test i've checked that apexcharts project does not uses `toHaveBeenCalled`, and in this case the only good way to unit test is to check if `this.drawLegends()` was called inside Legend.js. so i decided to not add new ways to unit test
- as for e2e i didn't understand how to add sample for generation. if you can give me some reference or describe how to do that - i might add …
=> Legend showForSingleSeries with no data issue fix

BACKERS.md
Just fixed your patreon link in Backers.md: When clicking on github it was parsed as a relative link and broken.
=> broken link to patreon not being displayed on github correctly

src/modules/Core.js
Brush selection removes multiple y axis on the main line/area chart. PR improves this behavior.
Fixes
https://github.com/apexcharts/apexcharts.js/issues/1455
https://github.com/apexcharts/apexcharts.js/issues/801
=> Fix brush chart selection with multiple y axis

src/charts/Pie.js, src/modules/settings/Options.js
Adds a property named 'startAngle' that determines where pie or donut charts start drawing.
=> Add 'startAngle' property to pie and donut charts

src/modules/Data.js
The code was validating a timestamp by checking if the number of digits was equal to 13. However, dates before 08/08/2001 have a 12 digit timestamp.
I changed the code to validate the timestamp by checking if the number has length 12 or 13.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings
- [ x ] New and existing unit tests pass locally with my changes
=> Fixing timestamp for older dates

src/charts/HeatMap.js
Set HeatMap's baseline color for dark mode -- original light mode works as before.  Coloring is still a bit off from the default dark background, but this way of coding is consistent with [other places in the codebase](https://github.com/apexcharts/apexcharts.js/blob/47b97082117d899d86b866bc779ea1e5a649c51a/src/modules/Theme.js#L82).
This addresses: https://github.com/apexcharts/apexcharts.js/issues/1532
=> Set HeatMap's baseline color appropriately for dark mode.

src/modules/annotations/Annotations.js, types/apexcharts.d.ts
This is a new feature that allows lines to be drawn as shape annotations. The motivation was to start partially addressing feature requests like #1280 as we wanted to do simple annotations on radial charts. Though more work would be required to address #1280 as it would be good to get it working like points annotation, it's a start 😄.
=> Draw lines as shape annotations

dist/apexcharts.js, src/modules/helpers/UpdateHelpers.js
We use react-apexcharts and got a similar problem than this one: https://github.com/apexcharts/react-apexcharts/issues/143
After some digging, the problem occur when we change the options, and after, we change the series. This is the fix I propose for this problem, please review carefully as I'm quite new to apexcharts. Thanks!
=> Keep max an min axis in update options

src/modules/Data.js, src/modules/Fill.js, src/modules/legend/Legend.js, src/modules/settings/Globals.js
User can add a color prop to a series which will take priority over colors passed into the chart options.
Fixes #276 https://github.com/apexcharts/apexcharts.js/issues/276
=> Allow user to select color by series for axischarts

dist/apexcharts.js
Added additional checking to handle unhandled error when toggling visibility for candlestick.
There's an unhandled error when toggling visibility for candlestick when using XY format. Added checking to check to ignore if element is undefined when trying to access series' first element in the respective data array. Alternatively, the checking can be changed to checking the length of the data array as well.
=> Fix unhandled error when toggling visibility

src/modules/legend/Legend.js
This is the fix that was proposed in #761 by @RollingStone85. I tested it and it works well. Before the fix, no legend was printed (although the browser was set to print background colors) and after the fix it was displayed!
I hope this can be acceptable and can help others!
- [NA] I have commented my code, particularly in hard-to-understand areas
=> Fix for #761, no legend color when printing

samples/vanilla-js/timelines/multi-series-group-rows.html, src/charts/RangeBar.js, src/charts/common/bar/Helpers.js, src/modules/settings/Options.js
- Added a flag ‘rangeBarGroupRows’ to group rows (horizontal bars) together in a multi-series timeline chart
- Added a example html page to samples
Fixes #1418
=> Add flag to group rows together in a multi-series timeline chart

src/charts/Pie.js, src/modules/dimensions/Dimensions.js
Hi, I faced with [some problems](https://codepen.io/funkir/pen/povyOPX) on the pie \donut charts, when I used legend. This PR fixes them.
=> fixed circle chart size when show legend

types/apexcharts.d.ts
Add typing for the new `plotOptions.bar.rangeBarGroupRows` option.
Fixes #1418
=> Add typing for rangeBarGroupRows option

src/apexcharts.js, src/modules/settings/Options.js, types/apexcharts.d.ts
Hi, I am using graphics inside an iframe that dynamically changes its height. This triggers the resize event and all charts start updating. Is such a solution to this problem possible?
=> removes unnecessary update when window height changes

package.json
Rollup related NPM packages should be listed in devDependencies
Fixes installation warnings like this:
```
[3/5] 🔗  Linking dependencies...
warning "apexcharts > @rollup/plugin-babel@5.2.1" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
warning "apexcharts > @rollup/plugin-babel > @rollup/pluginutils@3.1.0" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
```
=> Move @rollup/plugin-babel to devDepenendencies

src/modules/Range.js, tests/unit/bar-chart.spec.js
`minXDiff` must be computed using the sorted array instead of the original array.
Fixes #2140
=> minXDiff must be computed using the sorted array

src/apexcharts.js, src/modules/Graphics.js
Changing the position error of the title of horizontal graphs
=> fix y-axis title position in horizontal bar charts when labels are long

src/charts/RangeBar.js
When using a ranged bar chart and having a point in the series where either y1 or y2 is zero, apexcharts wouldn't use the formatter. This caused half of the bars in our chart to use the default formatter even though we had given our own in the options.
=> FIX: Fixed y axis formatter not working when range contains zero

src/modules/Exports.js
The exported CSV-file is missing a byte order mark (BOM). This causes Excel to misinterpret the file and gets the encoding wrong. This PR adds a BOM to the beginning of the CSV-file.
Fixes #1629
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
=> Fix for #1629, adds BOM to CSV export

src/modules/dimensions/YAxis.js
Using multiple Y-axis (6) there were visible problems with spaces between them.
yaxis[i].labels.rotate and yaxis[i].title.rotate were not properly used when computing the bounding boxes
=> dimensions/YAxis: correct label/title rotation for computing Y-axis width

src/modules/TimeScale.js, src/utils/DateTime.js, tests/unit/data/sample-data.js, tests/unit/timescale.spec.js
Currently smallest labels shown for `datetime` scale is 5 minutes:
https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/TimeScale.js#L223-L227
I kept 5 minutes labels for 15+ minutes ranges and added 1-minute labels for smaller ranges.
Fixes #2227
=> feat(TimeScale): show label for every minute on small scale

samples/playground/options.js, src/modules/TimeScale.js, src/modules/settings/Options.js, tests/unit/data/sample-data.js, tests/unit/timescale.spec.js
Added ability to show labels for seconds on `datetime` scale:
* for intervals from 1 to 5 minutes — every 10 seconds
* for intervals from 20 seconds to 1 minute — every 5 seconds
* less than 20 seconds — every second
Fixes #2278
=> feat(TimeScale): added seconds scale

src/modules/axes/XAxis.js, src/modules/axes/YAxis.js
Title element was not added to the text element for Y-axis label. This resulted in the full-text tooltip did not show when hovering over the text of the label
Fixes #2281 (Maybe something else)
=> Add title element for Y-axis labels

src/modules/dimensions/YAxis.js
minWidth doesn't always work if the formatter has been set.
Take a look at this example
https://codepen.io/github-rj/pen/vYxZbXg
minWidth doesn't always work when the formatter has been set. I suggest comparing Label's minWidth to arrLabelrect.width and rect.width. If minWidth is greater than arrLabelrect.width or rect.width, this is used as the width of the label.
=> minWidth doesn't always work

src/modules/annotations/PointsAnnotations.js
Annotation point is displayed in the wrong position when many series are associated with the same axis
https://codepen.io/github-rj/pen/KKVGWLg?editors=0010
I will explain the problem using an example.
In this example, I have four series:
- serie-1 and serie-2 have axis 0.
- serie-3 has axis 1.
- **_serie-4 has axis 2_**.
I want to have a annotations point on serie 4.
```
annotations: {
points: [
{
x: 1595226611882,
y: 69,
yAxisIndex: 2,
seriesIndex: 3,
label: {
text: "Point Annotation (XY)"
}
}
]
```
I always thought that seriesIndex has to be 4, but after reading the code I realize that serieIndex has to be 3( if I'm wrong please correct me). I set yAxisIndex to 2 and seriesIndex to 3.
The yAxisIndex was used to calculate the y position (index of array). I think this can be seriesIndex …
=> Annotation in wrong position

src/modules/Markers.js, types/apexcharts.d.ts
Adds ability to change a shape of discrete markers:
=> Add shape to discrete markers

README.md
- Correct link (it's moved to the `apexcharts` org a while ago)
- Moved to the "official" block of wrappers (as it's owned by the `apexcharts` org) - This is just a suggestion
=> Updates for stencil-apexcharts wrapper

types/apexcharts.d.ts
The following type definitions were missing:
```
exportToSVG?: string
exportToPNG?: string
exportToCSV: string
```
Fixes #2563
=> missing locale types in ApexLocale.options.toolbar

src/charts/common/bar/Helpers.js, types/apexcharts.d.ts
`plotOptions.bar.borderRadius` now excepts both a number and a number array.
This PR is a combination of a bug fix and a new feature.  By allowing `plotOptions.bar.borderRadius` to accept both a `number` and a `number[]`, developers can now apply a border radius to a specific series in their chart.
Fixes #2592
The `borderRadius` property now behaves as follows:
`borderRadius: 5` - when setting the border radius to a number, there is **no change in behavior**. All series will receive the same border radius value. Unless it's a stacked bar chart. In that case all series would have a border radius of 0 except for the last series in the stacked bar chart.
`borderRadius: [5, 10, 5, 3]` - when setting the border radius to an array, the border radius value will be applied to each series …
=> Added support for series specific border radius on bar chart

types/apexcharts.d.ts
Add `ApexFill.gradient.colorStops` property on the typescript declaration.
https://apexcharts.com/docs/options/fill/#colorStops
Fixes #2656 
=> Add fill.gradient.colorStops declaration

build/config.js, src/apexcharts.js, src/modules/helpers/InitCtxVariables.js, src/utils/Utils.js
Previously, all ApexCharts CSS was injected in the `<head>` of the document ApexCharts was included in, through [StyleInject](https://github.com/egoist/style-inject/blob/master/src/index.js) that was being called by [`rollup-plugin-postcss`](https://github.com/egoist/rollup-plugin-postcss).
This PR disables the automatic injection, and instead injects it manually. We first check if we're in a Shadow DOM context, and append the CSS to the shadow root if so. Otherwise, we check if the CSS has already been added to the current document, and insert it if not.
While the primary goal of this PR was to fix the Shadow DOM problem, it introduces a few other improvements:
- Since the injection is now context-aware, even for non-shadow contexts, we inject in the chart element's document, not the …
=> Inject ApexCharts CSS to shadow root if we're in a shadow DOM context

src/modules/annotations/YAxisAnnotations.js
=> Fixes yaxis annotations at the very top edge of the graph that are displayed at the wrong y-coordinate

src/modules/CoreUtils.js, src/modules/Scales.js
Fix for not rendering 0 as min when using logarithmic
Fixes https://github.com/apexcharts/apexcharts.js/issues/2673
=> Fix for not rendering 0 as min when using logarithmic

types/apexcharts.d.ts
As documented (https://apexcharts.com/docs/options/markers/) marker colors may be a single Color, but currently Typescript users get a type error when trying to do so.
```typescript
markers: {
size: 3,
colors: "#000000" as unknown as string[], // only string[] is allowed, but string works fine
}
```
is currently needed as a workaround
=> (type fix) Allow string for marker colour

src/charts/common/bar/Helpers.js
Fixes #2957 
When drawing bars and trying to find `backgroundBarColor` for the current value, if the index `j` is greater than the given `backgroundBarColors` array, it is being reduced by the length of the array. However, this is not sufficient to map a value to the range of an array (think of an example of j being 4, and the array containing a single value). The mod of the index should be calculated and updated.
=> fix: wrong mapping an index to the length of array

src/modules/tooltip/Labels.js
The main cause of the issue was irrelevant value for backgroundColor for the markers inside tooltip (pColor): if fill type was "pattern", we had 'url(#patternId)' instead some color. This solution works for each of pattern style.
Fixes #2668
=> Fixed a label marker color for 'pattern' fill type

src/modules/tooltip/Utils.js
There was two causes:
- shifting one of arrays because of added extra point 0.000001 only for one axis. Fixed by adding the extra point to another one (needed to show the first marker);
- closestInMultiArray function worked well but not as expected. In case if a cursor is closer to a point on another x-axis which has a blue color, we will see active blue marker even if green graph seems to be closer on y-axis. So firstly, we should find the closest point on x-axis and than choose wich graph is closer on y-axis.
Fixes  #689
=> Fixed positioning of a tooltip in multi-series chart

samples/source/bar/bar-with-group-labels.xml, samples/vanilla-js/bar/bar-with-group-labels.html, samples/vue/bar/bar-with-group-labels.html, src/modules/Data.js, src/modules/axes/Grid.js, src/modules/axes/XAxis.js, src/modules/dimensions/Dimensions.js, src/modules/dimensions/XAxis.js, src/modules/settings/Globals.js, types/apexcharts.d.ts
Added sub-groups for xAxis. This allows for 1 level of groupping in the xAxis and is something offered by other apps like excel.
To achieve this the model is the following: 
```
{
chart: {
type: 'bar',
},
series: [{
name: 'sales',
data: [30, 40, 45, 50, 49, 60, 70, 91, 125, 10]
}],
xaxis: {
categories: [12, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 10],
group: {
groups: [{ title: "Test", cols: 3 }, { title: "Test1", cols: 2 }, { title: "Test2", cols: 4 },],
},
title: {
text: "AAA"
}
}
}
```
The fact that you can specify the number of columns each group takes gives a lot of flexibility to do any combination you want
=> feat: Add sub-groups in xAxis labels

src/modules/CoreUtils.js
I've recently created a PR:  https://github.com/apexcharts/apexcharts.js/pull/3027  to fix a bug in logarithmic scale chart that height of bars isn't aligned with the values given to them:   https://github.com/apexcharts/apexcharts.js/issues/2909 .
However, I found that In my fix, when using logarithmic scale with y-axis value is lower then 1 , then the calculation of the height of this bar is wrong.
This PR is in order to fix this bug.
=> Fix bug when Y-axis value below 1 in logarithmic scale chart

src/modules/helpers/UpdateHelpers.js
Fixes multiple bugs with calling `updateOptions` when one or more series are hidden:
- Y-Axis was not sized appropriately to visible series
- Un-hiding series did not show full data set
=> Fix bugs with collapsed series data on updating options/series

package-lock.json, src/charts/Line.js, src/modules/settings/Defaults.js, src/modules/settings/Options.js, yarn.lock
Adds the ability to have both line and area paths fillable with a gradient (and any other fill option).
=> Add ability to use gradient fill on line and area at the same time

src/modules/Exports.js
Fix JS error when no scale is specified... Just set it to 1.
https://github.com/apexcharts/apexcharts.js/issues/3144
- [X ] Bug fix (non-breaking change which fixes an issue)
(I haven't added any tests but it's a very basic simple change)
=> When no scale is specified in getSvgString() treat as 1

types/apexcharts.d.ts
OpacityFrom and OpacityTo are described in the documentation as supporting both numbers and an array of numbers. The array of numbers is supported by the application and the type should be updated to reflect this capacity.
=> Update types to reflect Documentation

src/utils/Resize.js
Signed-off-by: Miki <miki@amazon.com>
When the element passed to ApexCharts is a child of a ShadowRoot, the resize helper attempts to get the dimensions and display type of its parent. Since the parent is the ShadowRoot, both of those attempts fail. The same would happen for any DOCUMENT_FRAGMENT_NODE node type.
=> Fix failure to render when the chart element is a child of a shadow root

src/modules/helpers/UpdateHelpers.js
we should use new options for updating min/max yaxis when updating StackType to 100%
[Fixes # 3208](https://github.com/apexcharts/apexcharts.js/issues/3208)
=> use new options while updating yaxis min max for stackType

src/modules/Scales.js
My fix contain the solution at autoScaleYaxis that for all zero values in a series not show line chart
=> fix: fixed autoScaleY for all zero values in array

types/apexcharts.d.ts
Remove extra semicolon in ApexOptions type
=> fix: ApexOptions type semicolon

types/apexcharts.d.ts
Adds Seconds to X Axis Datetime Formatter to allow displaying time with seconds when showing graph over a small amount of time. Updates this Datetime Formatter to match the other Datetime Formatters in the project.
=> Added Seconds to X Axis Datetime Formatter

src/modules/Exports.js, tests/unit/downlaod-csv.spec.js
The main problem was on line 263 in Export.js:
`if (s.data && s.data.length) `
If first series data was an empty array it was skipping for cycle to fill all csv columns.
My changes on Exports.js for exportToCsv method are quite simple:
basically I've made sure that all collapsed series have an array with empty values to build correctly csv data structure.
=> 3365 Fix deselect first series exports empty csv

types/apexcharts.d.ts
The type of track background in radial bar has been changed to fit the [following specification](https://apexcharts.com/docs/options/plotoptions/radialbar/#trackBackground) in the documentation. In the description it says: "Color of the track. If you want different color for each track, you can pass an array of colors.", and indeed it works as described, but the typescript declaration of this property is inconsistent, as it doesn't  accept an array of strings. I noticed this problem when using the chart in a project I work on, and had to appeal to "ts-ignore" to solve it.
I haven't found any issue related to this problem, but I think it makes sense to solve it now.
=> Declaring correct type for track background in radial bar

src/assets/apexcharts.css
Labels of series with a `:hover` effect have a tiny (`3px`) area between the dot and the text in which the `:hover` effect is discontinued (not hovered). 
This PR fixes the issue, without any regression.
Supported by all browsers.
Example chart showcasing the bug: https://apexcharts.com/react-chart-demos/heatmap-charts/color-range/
=> Fix legend labels hover between dot and text

src/modules/TimeScale.js, tests/unit/timescale.spec.js
Fixes #3483. The underlying issue was that some x-axis ticks would end up in the wrong position, overlapping in some cases and being deleted by the code to ensure ticks don't overlap. This seems to be because the first tick on the x-axis has its position adjusted in two places: first by setting and adjusting `firstTickPosition` according to `remainingMins` on line 620, and then again inside the loop - which I remove in this change.
I've also added a unit test which fails under the old code. This test makes sure that the `generateHourScale` function generates x axis ticks which do not overlap under the conditions seen in #3483.
Before:
After:
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~ - no comments needed for …
=> #3483 Fix x-axis tick alignment

src/modules/Markers.js
Markers renders outside graph area, which is not so nice.
Codepen that demonstrate the bug: https://codepen.io/leinonen/pen/xxaqmrX
Fixes #3320, #3562
Avoid rendering markers that are outside the graph area.
=> fix: don't render markers outside graph area

src/charts/BoxCandleStick.js, src/modules/Core.js, src/modules/tooltip/Position.js, src/modules/tooltip/Tooltip.js, src/modules/tooltip/Utils.js
Prevent tooltip being stuck for mixed line & candlestick charts when first series type is candlestick and all other (line) series are hidden.
=> Prevent stuck tooltip for line & candlestick charts

src/modules/tooltip/Utils.js
When the `markers.size` config is set and any series has discrete markers, the result of `getElMarkers()` was an empty `NodeList` for all series. This prevented all markers in all series from reacting to hover events and the tooltip from positioning relative to markers.
[Codepen](https://codepen.io/idpaterson/pen/YzOLYYR) where you can observe the tooltip and marker effects on hover by toggling the variables `enableDiscrete` and/or `enableMarkerSize` to false to modify the chart config.
This issue was introduced in v3.33.2 by removing the `.apexcharts-series-markers` class name when the chart has discrete markers. That change was made in order to add padding to discrete markers on sparklines in d6ae287. The original purpose of removing this class name was for charts with null values …
=> Fixes empty getElMarkers() for all series when any series has discrete markers and a global size is set

src/modules/Data.js
I removed the condition for the chart.type to be exclusively 'bar', otherwise when we mix types, we get undefined instead of 0 on stacked bars
Before:
After: 
Fixes #3811 
=> [bugfix]: set Null values to 0 when cnf.chart.stacked 

src/charts/Treemap.js, types/apexcharts.d.ts
FIxes #3914 
If accepted, this PR will: 
- Add dataLabels field to treemap plotOptions: `dataLabels?: { format?: 'scale' | 'truncate' }`
- Add new method that will truncate label text after formatter has been applied, based on config
- Utilize existing methods/utils such as `getTextBasedOnMaxWidth` and `rotateToFitLabel`
- Update `rotateToFitLabel` to improve vertical alignment and appearance of larger truncated labels
Treemaps with dynamic label lengths can easily become unreadable when they are long with the current fontSize scaling method. Users should have access to a config option where a label uses a consistent font size and will automatically trim/truncate itself to fit within its rect.
=> Feat: trimmed treemap labels

types/apexcharts.d.ts
When using Typescript (react-apexcharts in my case) there is no posibillity to target multiple charts with brush. This PR should fix it. 
*that's my first PR on Github ever, also first contribution to someone's package, so if I've done something wrong please correct me.
Fixes #3917  (issue)
=> Added type of string array to brush targets.

src/modules/TimeScale.js, tests/unit/timescale.spec.js
Adds additional date switch for the first element in generated hours labels array. 
Fixes #3915 
=> Bugfix: Double rendering of labels

types/apexcharts.d.ts
The documentation shows that `colorStops` is an array of objects but the types have them as `any`.
Would be nice to have the types here when overriding the stops of a gradient.
Docs:https://apexcharts.com/docs/options/fill/
=> Added type to colorStops in ApexFill

src/modules/tooltip/Utils.js
This is related to #3798. The problem here is that we add a new control points that will always be closest to user's cursor position that first ones.
Fixes #3798
=> fix: detect positioning for leftmost values

src/charts/Line.js, src/charts/common/line/Helpers.js, src/modules/Range.js, src/modules/settings/Options.js, src/modules/tooltip/Labels.js
When adding multiple lines to an existing stack bar chart, the lines are also stacked rather than being expressed independently. That is, where line series 1 has a value of 10 and line series 2 has a value of 5 series 2 will be plotted at 15, not 5.
New Options:
chart.stackOnlyBar = true
tooltip.hideEmptyShared = true
Fixes #907 & #2076
=> feat: allow stack bar only

src/modules/ZoomPanSelection.js
I believe it's currently not possible to use the 'brush' feature with rangeBars charts. JavaScript raises errors because the code attempts to read fields from null objects (e.g., w.globals.xAxisScale).
I have attempted to implement a clean and minimal fix, closely resembling the existing code. Each change is wrapped within an 'if (w.globals.isRangeBar)' condition to avoid interference with other features.
Fixes 
I didn't file an issue, but someone raised the problem earlier this year: https://stackoverflow.com/questions/75618138/a-combination-of-two-rangebar-charts-in-apexcharts-but-brush-chart-does-not-work
=> bug fix: allow brush with rangeBars

samples/react/timelines/brush-rangebars.html, samples/source/timelines/brush-rangebars.xml, samples/vanilla-js/timelines/brush-rangebars.html, samples/vue/timelines/brush-rangebars.html
This is a demo for the brush function with rangebars, after fix #4071
I hope it's nice and clear
just a new demo file: new xml file, + the 3 html files that were generated automatically
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
=> added a demo for rangebar brush

src/apexcharts.js, src/modules/legend/Helpers.js, src/modules/settings/Options.js, tests/unit/nonce.spec.js
Allows a `nonce` setting to be set for created `<style>` elements.
Fixes #727 
=> allow nonce values for style elements

src/modules/Exports.js, src/modules/Toolbar.js, tests/unit/download-csv.spec.js
This change introduces CSV export of the datetime series with unequal X-axes. I know it is non-trivial to export data as CSV in the case of multi-series with variable X values, but it is still possible, at least for datetime series. It's an important and long-awaited input (given the issue referred below), and it also seems quite reasonable, since such data is seamlessly displayed on the timeline, thus should be available for export even with empty cells.
Fixes #1568
=> Handle CSV export of the datetime multi-series with variable X-axes

src/modules/Graphics.js, types/apexcharts.d.ts
[issue 868](https://github.com/apexcharts/apexcharts.js/issues/868)
This was never actually addressed
=> Added 'X' and '+' marker shapes 

src/charts/Bar.js
Fixes # 4121
Avoid large delays in combo charts that include bars, specifically when mixing X series with highly disparate numbers of data points. The sample from the issue renders a >3000 point line with a single point bar.
With animations turned off, chart rendering time fell from 16.5 to 0.37 seconds (from 32.5 to 1.3 seconds, with animations).
The reduction comes from not constructing the >3000 phantom bars with their corresponding DOM elements as a workaround to enable tooltips to be displayed for every datapoint.
There was no observed change to any of the e2e test sample charts or their tooltips following this change.
Downside: after this change, the default options will only show tooltips for each bar (the series drawn first).
Upside: broaden application of apexcharts to a category …
=> Issue #4121: plotting a mixed line and column chart with different xaxis datasets

src/modules/ZoomPanSelection.js
I debuged ZoomPanSelection.js and understand touchstart and touchend evenst are not existed.
So i tried solve this just with touchmove event!
Tested with react-apexchart examples and fortunatly it s worked.
=> Fixed mobile touch issue in pan zoom selection

src/modules/Range.js
Bug introduced in 3.46.0 caused collapsed series' to be scanned for min and max values only to find null values, setting w.globals.hasNullValues, which causes the effects described in the issue report.
Fixes #4271
=> Issue 4271:

samples/react/area/multi-axis-with-seriesname-arrays.html, samples/source/area/multi-axis-with-seriesname-arrays.xml, samples/vanilla-js/area/multi-axis-with-seriesname-arrays.html, samples/vue/area/multi-axis-with-seriesname-arrays.html, src/modules/Data.js, src/modules/Range.js, src/modules/Scales.js, src/modules/axes/AxesUtils.js, src/modules/settings/Globals.js
Add code necessary to handle collapsed series for charts that use the new yaxis: seriesName: as an array feature (to reference multiple data series'). 
The incorrect yAxis was  being hidden as series were collapsed. Also, a yAxis can only be hidden while all of the series' referenced by it are collapsed. Fixed the tooltip formatters in the sample `multi-axis-with-seriesname-arrays.xml` to detect undefined label values (as per established practice found in other samples).
=> Handle collapsed series when yAxis seriesName arrays are used.

samples/react/mixed/line-column.html, samples/source/mixed/line-column.xml, samples/vanilla-js/mixed/line-column.html, samples/vue/mixed/line-column.html, src/modules/DataLabels.js
Hide datalabels when the series is collapsed.
Also:
sample/source/mixed/line-column.xml: remove xaxis options overriding the labels option (X axis ticks and axis labels were not aligned with datapoints or columns).
Both these issues predate 3.46.0 changes
=> Hide datalabels when the series is collapsed.

src/modules/Scales.js
Fixes a bug in my earlier merged pull request related to collapsed series. Yaxes with a single referenced series that was collapsed remained visible.
=> Y axis hiding bug fix

src/modules/Formatters.js, src/modules/Range.js, src/modules/Scales.js
In zoomed charts, ensure the Y axis scale fits the full min..max range of Y values. Observed when looking at an unrelated bug report involving a zoomed brush chart with category based X axis.
Visual improvement to Yaxis scale:
For an all-integer series, prune fractional ticks when the number of ticks is greater than the range. For example, a range of 4 with 7 ticks (1,1.5,2,2.5,3,3.5,4) is reduced to (1,2,3,4).
A related change was made to the defaultYFormatter() routine for integer-only series/charts, to convert labels toFixed(1) only if the label does not match the Y value. This replaces the previous condition that converted all integer-only series labels to toFixed(1) if the range of the series was < 5. In the previous para example would unexpectedly emit the labels (1.0,2.0,3.0,4.0).
=> Zoomed scale fixes:

src/modules/axes/Grid.js
Fixes #4314
The issue can also be seen in the demo chart:
https://apexcharts.com/javascript-chart-demos/bar-charts/reversed-bar-chart/
Or more clearly in the sample: reversed-bar.html
=> Fix misalignment of chart to axis boundary in reverse bar charts.

src/apexcharts.js
The original code checked for the style element by using it's this.css, and when using ng-apexcharts (for example) having multiple components in a ShadowDOM resulted in multiple additions. So it wouldn't actually find the element and always add it again when in ShadowDOM. To solve this, it doesn't cache the style elem (using this.css) and uses a getElementById() from the ShadowRoot instead if in ShadowDOM, otherwise the usual document getElementById(). I've tested it and works nicely in and out of ShadowDOM in my tests.
=> [Fix] Use ShadowRoot getElementById() when in ShadowDOM.

samples/react/column/stacked-column-with-line-new.html, samples/react/column/stacked-column-with-line.html, samples/react/mixed/multiple-yaxes.html, samples/source/column/stacked-column-with-line-new.xml, samples/source/column/stacked-column-with-line.xml, samples/source/mixed/multiple-yaxes.xml, samples/vanilla-js/column/stacked-column-with-line-new.html, samples/vanilla-js/column/stacked-column-with-line.html, samples/vanilla-js/mixed/multiple-yaxes.html, samples/vue/column/stacked-column-with-line-new.html, samples/vue/column/stacked-column-with-line.html, samples/vue/mixed/multiple-yaxes.html, src/charts/Bar.js, src/charts/BarStacked.js, src/charts/BoxCandleStick.js, src/charts/Line.js, src/charts/Radar.js, src/charts/RangeBar.js, src/charts/common/bar/Helpers.js, src/charts/common/line/Helpers.js, src/modules/CoreUtils.js, src/modules/Scales.js, src/modules/ZoomPanSelection.js, src/modules/annotations/Helpers.js, src/modules/annotations/PointsAnnotations.js, src/modules/annotations/XAxisAnnotations.js, src/modules/annotations/YAxisAnnotations.js, src/modules/axes/AxesUtils.js, src/modules/axes/Grid.js, src/modules/tooltip/AxesTooltip.js
Fixes relating to yaxis.seriesName array feature added at revision 3.47.0:
1) The forward and reverse yaxis to series maps had errors.
2) Anything that indexed into various global or context arrays (yaxis array, series working arrays, baseline or ratio arrays, etc), needed to be mapped through the new forward or reverse yaxis to series maps.
Fix historical issue with goals and annotations being drawn when the axis is hidden or outside the grid area when zoomed or panned, or where rectangular area annotation should be clipped.
Fix historical issue: baseLineY calculation not adjusted for logarithmic y axes.
Miscellaneous:
1) Remove yaxis.min: 0 from the bar axes in sample as not required.
2) Fix several calls to CoreUtils.getLogVal(b,d,seriesIndex) that were missing the 'b' (base) argument. …
=> Multiple-yaxis-scales, 3 series with 2 scales demo was broken by 3.47.0

src/apexcharts.js, src/modules/Core.js, src/modules/CoreUtils.js, src/modules/Range.js
The default type for chart is "line" and the default for series is the chart type, therefore, if the types of all series match the chart type, this should not be considered a combo chart. Previously, if any series had a defined type, the chart was considered a combo chart.
Fixes #4132
The CodePen example in the original  bug report will stack correctly with this fix, but as far as I know it doesn't restore the behaviour the reporter claims was working in revisions prior to 3.44.1.
=> If all series types match the chart type it isn't a combo chart

src/charts/Line.js, src/modules/Scales.js, src/modules/ZoomPanSelection.js, src/modules/axes/Grid.js, src/modules/tooltip/AxesTooltip.js, tests/unit/multiple-scales.spec.js
Additional fixes for indexing errors using yaxis-series mappings after seriesName-as-an-array feature implementation.
Add additional checks to manage old and new modes.
Unit tests targeting seriesName-as-an-array feature have been modified and expanded to "prove" yaxis-series forward and reverse mapping correctness.
Context:
Backward compatibility requires that various data structures be indexable by either the yaxis index or the series index at different times, which rely on the old one-to-one correspondence [in multi axis charts]. The new seriesName-as-an-array feature removes this correspondence and implements forward and reverse maps to bridge compatibility, nevertheless, every reference into those arrays in the codebase needs to be discovered and adjusted. All instances that have so …
=> Fixes issue 4340

src/charts/Line.js, src/modules/Range.js
Area and line paths must cover the full unbroken segment to render gradients correctly. Separate paths for each datapoint did not work.
Miscellaneous:
1) Fix reference to stroke curve that assumed object would be a string (can also be an array).
2) For completeness, add breaks to switch cases in getMinYMaxY(). Not having them was completely benign.
Fixes #1570
Fixes #4271
Fixes #3555
=> Fix gradient fill glitches for series with nulls.

src/modules/tooltip/AxesTooltip.js
=> Invalid reference in Y axis tooltip text routine

src/charts/Line.js
There is still an issue with the pathTo and pathFrom path arrays used in animations not handling null data. This causes some glitching during animation.
This fix only affects smooth curves. Will look at straight line plots next.
Fixes #3525 (mostly)
=> Fix for fill fragmentation in rangeArea plots with nulls in data

src/modules/Series.js
In addition to the series and datalabels, highlight the referenced yaxis on legend series hover. This is an added visual aid that is useful in multi-axis charts, and generally to identify the reference Y axis.
=> Extension of the legend hover series highlighting to include the reference Y axis

src/modules/Scales.js
Add a missing conditional block designed to ensure the range remains a multiple of stepSize when min is defined. Was present in the max case but not the min case.
Record the absolute final tick number used in the grid alignment of following axes, that is, after pruning to maxTicks.
Fixes #4357
=> Fix for #4357

src/charts/Line.js, src/charts/common/line/Helpers.js
When determining if the series is stacked, when checking the type of the series use realIndex.
Fixes #4402
=> Fix issue 4402

src/modules/Scales.js
Fixes a bug introduced in a previous PR.
In Scales.niceScale() when the passed-in yMin and yMax indicate no data, cannot simply substitute w.globals.min and w.globals.max as the user may have configured one or both as a function, making it likely that the global min/max values are not suitable and which can cause undefined behaviour. Substitute sane default values in that case.
=> Fix a potential crash condition when collapsing series'

src/modules/Exports.js
I encountered a bug while attempting to export chart data to CSV from a line chart that had null datetime categories and values (to show inconsistencies of data over time), and I was getting the same error as described on #2101, #2185 and #3247. My fix simply checks if the current category is null and moves on to the next if such is the case.
Fixes #2101, #2185 and #3247.
=> Fixed bug with exporting to CSV when categories are null

src/modules/dimensions/Dimensions.js
This commit adjusts the `plotCoords` method to correctly handle cases where the stroke width (`stroke.width`) is provided as an array of values, which corresponds to different series in the visualization. Previously, the code assumed a single numeric value, leading to incorrect grid padding calculations when multiple series with different stroke widths were present. 
Now, the method checks if `stroke.width` is an array and uses the maximum value from this array for setting grid padding, ensuring that the largest stroke width is properly accommodated.
Changes include:
- Adding a condition to determine whether `stroke.width` is an array.
- Using `Math.max(...)` to find the maximum stroke width when necessary.
- Applying this maximum value to adjust `gridPad.top` and `gridPad.bottom`.
Fixes …
=> Fix issue 4216: grid padding calc to support array of stroke widths

src/charts/Bar.js, src/charts/BarStacked.js, src/charts/BoxCandleStick.js, src/charts/Line.js, src/charts/RangeBar.js, src/charts/common/bar/DataLabels.js, src/charts/common/bar/Helpers.js, src/modules/Core.js, src/modules/CoreUtils.js, src/modules/Data.js, src/modules/Range.js, src/modules/Responsive.js, src/modules/Scales.js, src/modules/axes/XAxis.js, src/modules/dimensions/Dimensions.js, src/modules/settings/Globals.js
Fixes corner cases and some basic omissions from earlier merged post-3.48.0 pull request to with series groups and stacking of series.
Updates to improve stacking of line-area type series to expand use cases, further leveraging the recent yaxis.seriesName as-an-array feature. Not really adding any new features but bridging some gaps that previously did not make sense to do using the existing config options.
Generalization of series group naming to apply to line/area series in similar way to how it applies to bar/column series.
It remains the case that only series of the same type can be stacked together.
Example:
The familiar grouped and stacked columns on one yaxis are charted together with three area series (on another yaxis, although that is not a requirement), two of those series, one …
=> Updates to improve stacking of line-area type series.

src/svgjs/svg.js
While checking out the repo, I noticed that there was an error in the build file. we should be using createElementNS instead of createElement for SVG elements. this fix addresses the issue I noticed.
=> Use createElementNS instead of createElement for svg objects

types/apexcharts.d.ts
#4247 now allows or requires seriesName to be an array, and that wasn't reflected in the types. I wasn't able to find out which case it is, and even the documentation doesn't mention seriesName being an array, in one place it's a string, in another it's undefined.
=> Make YAxis seriesName an Array

src/charts/Line.js
Recent refactoring of line paths creation to fix various issues did not update the pathFromArea paths, upsetting animation morphing from those paths to final areaPaths.
1) Remove redundant graphics.move() from end of lower rangeArea paths.
2) Add closing line segment to pathFromArea path.
Fixes #4437
This has fixed the major issue but is still not perfect. There does appear to be an overall improvement visually over 3.45.2, the version preceeding the start of these refactoring efforts. If we compare, for example, the area-spline sample generated by 3.45.2 with that obtained after this patch, there is no longer a split between the line path and fill at every datapoint during the morphing process. There is instead a single artifact with the last datapoint that it would be nice to resolve. …
=> Area path animation glitching issues

src/modules/ZoomPanSelection.js
Reverts apexcharts/apexcharts.js#4240
=> Revert "Fixed mobile touch issue in pan zoom selection"

src/assets/apexcharts.css
The recent commit 9f1d327 introduced extra CSS selectivity that caused the exclusion of Y axes highlighting. This patch selectively re-adds those chart components.
The intent of commit 9f1d327 is unchanged by this PR.
=> Restore Y axis highlighting during legend series mouseover.

src/modules/Theme.js
Changing a chart from dark mode to light mode with the options object wasn't working (example at https://github.com/Sebastian-Webster/apex-reproducible-example)
This pull request fixes that issue so dark mode charts can be changed to light mode successfully
=> fix: fixed theme change from dark mode to light mode not working

tests/e2e/samples.js
This was done by adding a check to see if Node is running in a TTY environment. If it isn't in a TTY environment, logs are made with console.log instead of process.stdout.write() and process.stdout.clearLine().
=> fix: prevent issues with tests running in non-TTY environments

src/modules/Responsive.js
Revert an erroneous and ineffectual change introduced in 3.49.1 via commit  b6a6874. The remainder of that commit is still required.
Fixes #4519
=> Fix responsive options failure in 3.49.1

src/modules/Core.js, src/modules/Theme.js, src/modules/settings/Config.js, src/modules/settings/Options.js
Fixed the transparent background not appearing when a chart is in dark mode. Previously it would pull the background colour from the dark theme, and now it gets it from the chart options.
Fixes #4541
=> fix(#4541): fixed transparent background not appearing with dark mode

src/modules/Exports.js, src/modules/settings/Options.js, types/apexcharts.d.ts
We needed the numbers in a csv export to be formatted correctly with a comma as a decimal separator. So I thought it would be a good way to implement a numberFormatter like the dateFormatter for the CSV Export.
Sorry, I don't know how to write unit tests.
=> CSV Export numberFormatter

tests/e2e/samples.js
This PR fixes the test coverage report failing to generate on Windows by running nyc in a shell if the command is ran from a Windows machine.
=> Fixed test coverage report failing to generate on Windows

.github/workflows/stale.yml
The current version of actions/stale being used (v3) has been superseded by v9. The notable changes between v3 and v9 are:
- Upgraded Node.js from 12 -> 20
- If an issue is closed, it is now closed as `not_planned`instead of `completed`
- The action is now stateful, meaning that if the action ends because of `operations-per-run` then the next run will start from the first unprocessed issue and skip the issues processed during the previous run(s). The state will be reset when all the issues are processed
=> Updated actions/stale action

samples/source/line/realtime.xml, samples/vanilla-js/line/realtime.html, tests/e2e/samples.js
In #4515 a change was made to the line/realtime sample so that its setInterval would stop after 2 seconds so Puppeteer wouldn't timeout from waiting for the setInterval to be cleared. That change was not added to the XML file so whenever samples were rebuilt the test would start to cause an issue again.
This pull request adds that change to the XML file so the test won't cause issues when samples are rebuilt. This pull request also makes the setInterval stop after 2 seconds only if it is used in e2e testing.
=> fix: line/realtime test

src/modules/ZoomPanSelection.js
For backward compatibility after the yaxis.seriesName as-an-array feature was implemented, needed to compute a yLowestValue and yHighestValue for each configured yaxis, not just the effective (visible?) yaxes.
Fixes #4561
=> Fix for issue 4561

src/modules/Range.js
Fix getMinYMaxY() handling of multiple Y values per X value that was broken sometime after revision 3.45.2 following changes to handle chart y axis autoscaling directly within this function.
Fixes #4560
=> Fix for issue 4560

src/modules/ZoomPanSelection.js
Bug:
In Safari 17.5, moving the mouse over a line or bar chart with a datetime x axis, while it is loading, results in "TypeError null is not an object (evaluating 'r.gridRect.getBoundingClientRect')". This is referenced in this issue thread: https://github.com/apexcharts/apexcharts.js/issues/1790
Fix:
A basic null check.
=> Add null checks on gridRect to avoid safari error

types/apexcharts.d.ts
In the documentation, [`legends.markers`](https://apexcharts.com/docs/options/legend/#markers) has a property `size` (in replacement for `radius` from my understanding). However [the type](https://github.com/apexcharts/apexcharts.js/blob/1dd87abb0dbc0c089f1c82cba34f647fabbcd876/types/apexcharts.d.ts#L826) for it is missing, hence causing an error in the project using this property.
Additionally, these `legends` properties are missing from the documentation but still present in the file:
- `textAnchor`
- `containerMargin`
- `markers.strokeColor`
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update
> [!NOTE]
> Not necessarily requires a documentation update but *might*.
=> Allow property `size` in `ApexLegend.markers`

src/charts/BarStacked.js
A regression introduced by commit 686266c (first appeared in release 3.49.0) caused stacked, reversed column chart with all negative series to render outside of masked plot area and not be visible.
Reduce/simplify the calculation of zeroH.
Fixes #4630
=> Fix regression issue introduced in 3.49.0

samples/react/column/stacked-column-with-line-new.html, samples/source/column/stacked-column-with-line-new.xml, samples/vanilla-js/column/stacked-column-with-line-new.html, samples/vue/column/stacked-column-with-line-new.html, src/modules/Scales.js, tests/unit/exponential-data.spec.js, tests/unit/small-range.spec.js
1. Unconditionally select default initial axis ticks based on SVG size.
2. Unconditionally, if not user specified, snap yMin or yMax to zero if already close.
3. Re-order yaxes in one sample chart to prioritize stacked column visual resolution. Add comment to draw attention to this feature of multi axis charts.
4. In Scales.niceScale: Check that maxTicks is always valid (suspect some Unit tests don't set SVG dimensions).
5. Set tickAmount explicitly in two unit tests to compensate for variation in scaling following the above changes.
Fixes #4632
=> Changes to accommodate issue 4632

src/charts/common/treemap/Helpers.js
Fix getShadeColor() handling of RGB values. Ensure hexToRgba receives a hex value by checking if the shadeColor() output is in RGB format; convert to hex if necessary before passing to hexToRgba.
#4645
=> Fix issue 4645

src/assets/apexcharts.css
summary of changes: in **src/assets/apexchart.css** added `direction: ltr !important;`  to ` .apexcharts-canvas`  class.
And the result: when the user uses apexchart.js the the ` .apexcharts-canvas` div inside `#chart` will always be **ltr** even if the user changes the app direction like: `direction: ltr !important;` won't affect the chart.
Fixes #4660
=> Fix: direction rtl the vertical text displaced

src/modules/Scales.js
```gl.seriesX[0].length()``` was effectively used to size a number of temporary arrays in ```Scales.scaleMultipleYAxes()``` but it appears that gl.seriesX is not populated if  ```tickPlacement: 'between'``` is configured, so this initialization now uses ```gl.datapoints``` instead.
Removed a duplicate version of a function that was left behind during previous refactoring:
```
Scales.setSeriesYAxisMappings()
CoreUtils.setSeriesYAxisMappings()
```
Both were identical except for a loop at the end of ```CoreUtils.setSeriesYAxisMappings()``` which set default series group names. Therefore removing ```Scales.setSeriesYAxisMappings()``` and substituting the call to it should have no net effect. This appears to be the case from testing.
Fixes #4704
=> tickPlacement: 'between' caused chart to crash

src/charts/Line.js
Remove unused variable (tidy-up, unrelated to the main issue)
Broken at revision 3.49.0:
Explicitly check for single isolated points when creating paths for 'straight' and 'smooth' curves. Curve type 'monotoneCubic' already does this intrinsically due to the different algorithm employed.
Fixes #4686
=> Restore checks for single isolated data points

src/charts/common/bar/Helpers.js
Function ```createBorderRadiusArr()``` failed if no series are defined, eg when data series are expected to be loaded later via the update call. Two samples (axios and jquery) were failing during ```npm run e2e```
=> Fix createBorderRadiusArr

types/apexcharts.d.ts
The `dataLabels` formatter can return an array. It will display both string on a separate line.
You can see this usage in this demo: [Treemap color range](https://apexcharts.com/vue-chart-demos/treemap-charts/color-range/)
```js
dataLabels: {
...
formatter: function(text, op) {
return [text, op.value]
},
...
},
```
We can see further down in the code that the function is handling the case where `text` is an array: https://github.com/apexcharts/apexcharts.js/blob/483c471aeec4c9fa3401ed23cfe1219ba264da82/src/modules/Graphics.js#L693
----
The tooltip y formatter, accepts a second arguments (like many other formatter). It's `opts?: any` and is missing.
This one fixes #4762 
=> Update types to add missing arguments and return types

src/charts/Line.js
With a Line chart representing a time series, isolated points were trying to close a path. This PR fixes this issue by checking that the point is unique using the already present logic that was handling isolated points in between `null` values.
Current version (4.0.0) jsfiddle showcasing the issue: https://jsfiddle.net/kocz16s2/ 
=> Fix isolated point in line chart not closing path

src/modules/TimeScale.js
bugfix Display error Date when set xaxis first label close to next day
#4763 
Align the timeScale value where set timeScale unit to 'day' in generateHourScale
=> #4763 bugfix Display error Date when set xaxis frist label close to next day.

types/apexcharts.d.ts
…ned from string[] to (string | number)[].
The return type of the dataLabels formatter has been redefine
Fixes #4801
We need to document the fact that multi lines can be displayed using the formatter in dataLabels.
=> fix:#4801 The return type of the dataLabels formatter has been redefine

src/modules/tooltip/Labels.js
This PR addresses an inconsistency in the tooltip label behavior. Previously, on configuring tooltip for multiple y series, when a formatter function was provided only for the tooltip value, the title's default formatter applied differed from when no formatter was provided. Now, the title will maintain a consistent default format regardless of whether a value formatter is used alone.
Fixes #4811
=> fixes #4811

src/charts/BoxCandleStick.js, src/modules/CoreUtils.js
Translate to logarithmic values points of y-axis
for different parts of candle-like plot shapes.
Change-Id: Ia99917f3b8d2718dae24e34e0ab3110e1719c16f
Calculate logarithmic values for OHLC points if logarithmic scale is used.
Fixes #3284 (issue)
=> Fix logarithmic scale drawing candle-like shape

samples/vanilla-js/heatmap/inconsistent-timeseries.html, src/charts/HeatMap.js
Added x-axis check to include gaps into a heatmap. To be honest my code is more a "dirty fix" as i used some of the globals variables without knowing if that is the correct way to handle it. So please review the code carefully and if you know a better solution improve it.
Test:
Fixes #4809
=> Fix heatmap gaps and ticket alignment

src/modules/Core.js
The `setupBrushHandler` method of the `Core` class relies on the `ApexCharts` class' static `getChartByID` method. It calls this static method on the `ApexCharts` class directly without importing it currently.
This is fine if consuming `apexcharts` via
CDN / script tag as that places the exported `ApexCharts` class in the global scope, but it becomes an issue when users want to consume `apexcharts` via a package manager.
Update the `setupBrushHandler` method to call `ApexCharts.getChartByID` the `Core` class' `ctx` field instead.
Fixes https://github.com/apexcharts/react-apexcharts/issues/666
- - e2e tests passed locally
- - I haven't been able to verify that the unit test suite passes because they seem to be broken. I get the `getBBox is not a function` error when I run them, which I can …
=> Remove use of global `ApexCharts` class

package.json
The Angular compiler looks for the main field using a few fields in the package.json. The order it uses is:
- es2020
- es2015
- browser
- module
- main
The first entry the Angular compiler would find before this change was the 'main' entry point. This is however compiled as `common js` and Angular is looking for an `esm` so it would complain (it would still work though). Adding `es2020` as an entry point fixes this problem.
Fixes [ng-apexcharts#92](https://github.com/apexcharts/ng-apexcharts/issues/92)
=> Added support for the Angular compiler.

src/modules/Range.js
Previously, isFloat was being called on val before noExponents. This meant that if a value was particularly close to zero, it might pass the isFloat check but then be stripped down to just 0 by noExponents, which meant that getting the second element after splitting around the decimal point would fail.
This patch just does noExponent first so that if the value ends up being a round number, it doesn't enter that branch.
=> range: Fix getting decimal part of numbers close to 0

src/modules/tooltip/Tooltip.js
The main focus of this PR is highlighted in commit a9723f4 and 0a498a2, which fixes a visual glitch with the tooltip that occurred due to the early removal of its active state while users were interacting with the chart. This change leads to a smoother and more consistent user experience.
Other commits in this PR include optimizations that follow the primary fix, as well as a small optimizations of the existing code within the same function.
_Unfortunately, I wasn't able to run unit tests as there is some issue with them. Tests are not passing on the main branch (cb88426) either. However, it might be on my side. Checked on Windows 11 and in Github Codespace._
_Demonstration of the bug_
=> Fix tooltip stability for smoother chart interaction

src/modules/tooltip/Tooltip.js
Fixes [#4720](https://github.com/apexcharts/apexcharts.js/issues/4720)
This PR addresses an issue where the fixed option in the tooltip configuration for Pie/Donut charts was not working as expected. When `tooltip: { fixed: { enabled: true } }` option was set, the tooltip did not remain fixed in position.
The problem was caused by the tooltip position being recalculated by the`nonAxisChartsTooltips()` function, which overwrote the fixed position of the tooltip. The issue was resolved by changing the order of function execution so that `nonAxisChartsTooltips()` runs first, followed by the `drawFixedTooltipRect()` function that fixes the tooltip position.
=> Fix issue with fixed Tooltip not working on nonAxisChart

src/apexcharts.js
After [this commit](https://github.com/apexcharts/apexcharts.js/commit/5c3bba02849982cdcc5ec236ead609b50b593ae2#diff-c799981553c8e8e3e5321e944950ffef1fc4776a77b12bc138be46325bda1543R50), the `ApexChart` doesn't work with `Tabs` properly.  I made a demonstration setup  about the issue with Vue and Quasar frameworks:
https://codepen.io/siczmj/pen/vEYxBxL
You can see that the `ApexChart` appears on first rendering, but it disappears after tab switching. To reproduce it click on "Second" then on "First" tab. My investigation showed that this is caused by the invoked `destroy()` method added by the [linked commit](https://github.com/apexcharts/apexcharts.js/commit/5c3bba02849982cdcc5ec236ead609b50b593ae2#diff-c799981553c8e8e3e5321e944950ffef1fc4776a77b12bc138be46325bda1543R50).
By removing the …
=> Fixing unnecessary chart destroy on create

types/apexcharts.d.ts
There is support for multiline text already but it's missing in types.
=> Extend annotation label text type to array

src/modules/Graphics.js
The roundPathCorners function in the Graphics module conains a bug when dealing with e notation values. A path like this:
```
M -4.864179421768709 280.1277080745341 L -4.864179421768709 273.12454037267077 L -8.881784197001252e-16 273.12454037267077 L -8.881784197001252e-16 280.1277080745341 Z
```
is incorrectly parsed and the result is:
```
M -4.864179421768709 280.1277080745341 L -4.864179421768709 273.12454037267077 L e -16 273.12454037267077 L e -16 280.1277080745341 L -4.864179421768709 280.1277080745341 C -4.864179421768709 280.1277080745341 -4.864179421768709 280.1277080745341 -4.864179421768709 280.1277080745341 Z 
```
which leads to an svg parser error. The problem is with the following regex:
```
var match = part.match('([a-zA-Z])(.+)');
```
which incorrectly matches the e …
=> Fix incorrect parsing of e notation svg command values in graphics.roundPathCorners

src/modules/annotations/Helpers.js
.toFixed(10) was added in #4985 to address a clipping bug, but since it returns a string, direct comparison caused incorrect clipping.
Fixed by converting values to numbers with parseFloat() before comparison.
=> Fix comparison bug in clipping calculation

types/apexcharts.d.ts
This pull request addresses a TypeScript type error related to the `nonce` attribute within the ApexCharts options. While the functionality to include a `nonce` in the chart options already existed, the TypeScript type definitions were missing the correct type for this parameter, causing TypeScript projects to report errors. This PR adds the necessary type definition to the `ApexChart` interface in the `apexcharts.d.ts` file, ensuring proper TypeScript support.
This PR adds the correct type definition for the `nonce` parameter within the `ApexChart` interface in the global TypeScript types file (`apexcharts.d.ts`).
**Key changes:**
* Added the `nonce?: string` property to the `ApexChart` interface.
* This resolves TypeScript type errors that occurred when using the `nonce` parameter in …
=> Added nonce in the types in option.chart.nonce

types/apexcharts.d.ts
Includes the height property to xAxis type and removes the strokeWidth property which was being unused. The documentations is currently outdated for xAxis.axisBorder and yAxis.axisBorder, so it needs an update considering the new types.
=> Add a missing type and removes an unused type
